image: python:3.10 # Nebo jiná verze Pythonu, kterou preferujete

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Vypíše verzi Pythonu
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test_job:
  stage: test
  script:
    - echo "Spouštím testy..."
    - pytest tests/ # Spustí všechny testy v adresáři tests
    - echo "Testy dokončeny."
  artifacts:
    when: always # Uloží reporty i v případě chyby
    reports:
      junit: report.xml # Pokud chcete JUnit report pro GitLab UI (vyžaduje pytest-junit)
  # Pokud chcete JUnit report, přidejte do requirements.txt: pytest-junit
  # a upravte script:
  # script:
  #   - echo "Spouštím testy..."
  #   - pytest tests/ --junitxml=report.xml
  #   - echo "Testy dokončeny."